/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 /*
    @Ataullha
    CSE-2018
 */
package Jsoup;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class App {

    static String Tdesignation, Tname, Tmobilenumber, Temail;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        // scrap a website 
        // we are going to use imdb for that

        String depts[] = {"anp", "arc", "ban", "bmb", "bng", "cep", "cee", "che", "cse", "eco", "eee", "eng", "fet", "fes", "geb", "gee", "ipe", "mat", "mee", "ocg", "pad", "pge", "phy", "pss", "scw", "soc", "sta"};
        // website pme spelling wrong

        for (String dept : depts) {

            // Document doc = Jsoup.connect("https://www.imdb.com/chart/top").timeout(6000).get();
            /**
             * Ataullha*
             */
            Document doc = Jsoup.connect("https://www.sust.edu/d/" + dept + "/faculty").timeout(6000).get(); // connenct with internet is a must

            // get data from the imdb website 
            // Elements body = doc.select("div.department-faculty");  
            Elements body = doc.select("div.department-faculty li");
            //System.out.println(body1);
            // body we will get tbody.lister-list the name 
            //System.out.println(doc);
            // we will get the tr size 
            //System.out.println(body);

            if (dept.contains("pge")) {
                dept = "pme"; // for better understanding at this stage
            }
            if (dept.contains("ban")) {
                dept = "bba"; // for better undeerstanding at this stage
            }
            File file = new File(dept + "_contact.txt");
            file.createNewFile();

            FileWriter writer = new FileWriter(file);

            //writer.write(dept + "_contact[] = {");

            for (Element e : body.select("a")) {

                ///////Elements info = e.select("a");
                /**
                 * System.out.println(e.attr("data-title")); // name*
                 */
                Tname = e.attr("data-title");
                /**
                 * System.out.println(e.attr("data-designation")); *
                 */ // designation
                Tdesignation = e.attr("data-designation");
                //System.out.println(e.attr("data-description")); 
                String info[] = e.attr("data-description").split("<li>");
                for (String numandemail : info) {
                    //if(numandemail.contains("Email:") || numandemail.contains("Phone:"))System.out.println("--->>>>>>"+numandemail);
                    if (numandemail.contains("Phone:")) {
                        String num = numandemail.substring(6, numandemail.length() - 5).trim();
                        //System.out.println(num);// phone number...all
                        if (num.contains(",")) {
                            String Allnums[] = num.split(",");
                            /**
                             * *System.out.println(Allnums[0]);*
                             */
                            for (String val_num : Allnums) {
                                if (val_num.length() >= 11 && val_num.contains("01")) {
                                    Tmobilenumber = val_num;
                                } else {
                                    Tmobilenumber = Allnums[0];
                                }
                            }
                        } else if (num.contains(";")) {
                            String Allnums[] = num.split(";");
                            /**
                             * System.out.println(Allnums[0]);*
                             */
                            for (String val_num : Allnums) {
                                if (val_num.length() >= 11 && val_num.contains("01")) {
                                    Tmobilenumber = val_num;
                                } else {
                                    Tmobilenumber = Allnums[0];
                                }
                            }
                            }else if (num.contains("/")) {
                                        String Allnums[] = num.split("/");
                                        /**
                                         * System.out.println(Allnums[0]);*
                                         */
                                        for (String val_num : Allnums) {
                                            if (val_num.length() >= 11 && val_num.contains("01")) {
                                                Tmobilenumber = val_num;
                                            } else {
                                                Tmobilenumber = Allnums[0];
                                            }
                                    }
                                        }else {
                        /**
                         * System.out.println(num);*
                         */
                           // for(String val_num:Allnums){
                           // if(val_num.size()>=11 && val_num.contains("01")){
                        Tmobilenumber = num;
                           // }
                    }
                }else if (numandemail.contains("Email:")) {
                    String emails[] = numandemail.split("</li>");
                    String email = emails[0].substring(7, emails[0].length());
                    /**
                     * System.out.println(email);*
                     */ // email adress...all
                    Temail = email;
                }
                                    }
                            if(Tdesignation.isEmpty()) Tdesignation = " ";
                            if(Tname.isEmpty()) Tname = " ";
                            if(Tmobilenumber.isEmpty()) Tmobilenumber = " ";
                            if(Temail.isEmpty()) Temail = " ";
                            
                            String str = Tdesignation + "~~" + Tname + "~~" + Tmobilenumber + "~~" + Temail;
                            //writer.write("\"" + str + "\"" + ",");
                            writer.write(str+"~~~~");
                            //// System.out.println(info[1]);
                            //break;
                            //String info = e.attr("data-description");
                            //System.out.println(info);
//            String img = e.select("td.posterColumn img").attr("src");
//            // from tr we will select td and from td we will select td.posterColumn with img inside it img is the image inside it
//            // with the attr src
//            System.out.println(img);
//            String title = e.select("td.posterColumn img").attr("alt");
//            System.out.println(title);
//            String year  = e.select("td.titleColumn span.secondaryInfo").text().replaceAll("[^\\d]","");
//            // replace all the bracket with (2002) = 2002
//            System.out.println(year);
//            String rate = e.select("td.posterColumn.imdbRating").text().trim();
//            System.out.println(rate);
                        }
                        //writer.write("};");
                        writer.flush();
                        writer.close();

                    }

                }
            }
